Vagrant.configure("2") do |config|
  config.vm.define "mysql" do |mysql|
    mysql.vm.box = "ubuntu/trusty32"
    mysql.vm.hostname = "mysql"
    mysql.vm.network "private_network", ip: "192.168.50.10"
    mysql.vm.network "forwarded_port", guest: 3306, host: 3306
    mysql.vm.network "forwarded_port", guest: 80, host: 80
    mysql.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
  end
end